### ISSUE TITLE
[Fix]: 문의하기 기능 인증키 문제

### ISSUE THREAD

**Issue by FRONT-JB** [cyclops-operation/switter#46]
### 브라우저 환경

모든 브라우저

### 상황 설명

- 로컬에서 사용하는 문의하기 관련된 구글시트 인증키가 배포환경에서 제대로 동작하지 않는걸로 확인했습니다
  - 이로 인해 현재 문의하기 기능이 동작하지 않아 수정이 필요합니다. 

### 해결책

- VERCEL env 값 문제로 확인되어서 env 값을 변경해보고 수동 배포로 테스트를 진행해보겠습니다

**Comment by p-acid** [comment]
확인 결과 `env` 키 이름을 변경한 것을 노션 `.env` 에 반영하지 않아 이에 문제가 발생했습니다.  기존 `GOOGLE_SHEET_ID` 를 `GOOGLE_DOCUMENT_ID` 로 변경하면 문제가 해결되는 것으로 확인됩니다.

```env
GOOGLE_DOCUMENT_ID=10hlovz8bqquPshGmeGxqn4J2Lwbzmv6v9WMSEEf4hOM
```

**Comment by p-acid** [comment]
다른 테이블 형태의 Sass인 [에어테이블](https://www.airtable.com/)을 활용하는 것으로 결정.

- 배포를 진행하면서 발생했던 오류는 CD 스크립트 내 `actions/checkout` 플러그인의 버전 문제였던 것으로 확인되어, [플러그인 버전 업데이트로 해결](https://github.com/cyclops-operation/switter/pull/56/commits/73a80c8aab290aae67db420f7ee77c03d9750de1#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3)

**Comment by p-acid** [comment]
배포 버전 [1.0.5](https://github.com/cyclops-operation/switter/pull/56)에 반영되었습니다.
